const data = [
  {
    id: "1",
    brand: "Apple",
    name: "MacBook Air",
    precio: "25,000",
    description:
      "La notebook más delgada y ligera de Apple viene con los superpoderes del chip M1. Termina todos tus proyectos mucho más rápido con el CPU de 8 núcleos y disfruta como nunca antes de apps y juegos con gráficos avanzados gracias al GPU de hasta 8 núcleos. Además, el Neural Engine de 16 núcleos se encarga de acelerar todos los procesos de aprendizaje automático. Todo en un diseño silencioso sin ventilador que te ofrece la mayor duración de batería en una MacBook Air: hasta 18 horas. (1) Portátil como siempre, más poderosa que nunca.",
    serie: "A2337",
    year: "2020",
    ram: "8 GB",
    resolution: "full HD",
    screen: "13.3",
    battery: "18 h",
    chip: "M1",
    ssd: "256 GB",
    color: "Gris espacial",
  },
  {
    id: "2",
    brand: "Huawei",
    name: "celular",
    precio: "30,000",
    description:
      "La notebook más delgada y ligera de Apple viene con los superpoderes del chip M1. Termina todos tus proyectos mucho más rápido con el CPU de 8 núcleos y disfruta como nunca antes de apps y juegos con gráficos avanzados gracias al GPU de hasta 8 núcleos. Además, el Neural Engine de 16 núcleos se encarga de acelerar todos los procesos de aprendizaje automático. Todo en un diseño silencioso sin ventilador que te ofrece la mayor duración de batería en una MacBook Air: hasta 18 horas. (1) Portátil como siempre, más poderosa que nunca.",
    serie: "A2337",
    year: "2020",
    ram: "8 GB",
    resolution: "full HD",
    screen: "15",
    battery: "30 h",
    chip: "M1",
    ssd: "128 GB",
    color: "Azul",
  },
  {
    id: "3",
    brand: "Samsung",
    name: "Smart TV",
    precio: "35,000",
    description:
      "La notebook más delgada y ligera de Apple viene con los superpoderes del chip M1. Termina todos tus proyectos mucho más rápido con el CPU de 8 núcleos y disfruta como nunca antes de apps y juegos con gráficos avanzados gracias al GPU de hasta 8 núcleos. Además, el Neural Engine de 16 núcleos se encarga de acelerar todos los procesos de aprendizaje automático. Todo en un diseño silencioso sin ventilador que te ofrece la mayor duración de batería en una MacBook Air: hasta 18 horas. (1) Portátil como siempre, más poderosa que nunca.",
    serie: "A2337",
    year: "2020",
    ram: "8 GB",
    resolution: "full HD",
    screen: "13.3",
    battery: "18 h",
    chip: "M1",
    ssd: "256 GB",
    color: "Verde",
  },
  {
    id: "4",
    brand: "LG",
    name: "Audifonos",
    precio: "40,000",
    description:
      "La notebook más delgada y ligera de Apple viene con los superpoderes del chip M1. Termina todos tus proyectos mucho más rápido con el CPU de 8 núcleos y disfruta como nunca antes de apps y juegos con gráficos avanzados gracias al GPU de hasta 8 núcleos. Además, el Neural Engine de 16 núcleos se encarga de acelerar todos los procesos de aprendizaje automático. Todo en un diseño silencioso sin ventilador que te ofrece la mayor duración de batería en una MacBook Air: hasta 18 horas. (1) Portátil como siempre, más poderosa que nunca.",
    serie: "A2337",
    year: "2020",
    ram: "8 GB",
    resolution: "full HD",
    screen: "13.3",
    battery: "18 h",
    chip: "M1",
    ssd: "256 GB",
    color: "Rojo",
  },
  {
    id: "5",
    brand: "DELL",
    name: "Laptop",
    precio: "45,000",
    description:
      "La notebook más delgada y ligera de Apple viene con los superpoderes del chip M1. Termina todos tus proyectos mucho más rápido con el CPU de 8 núcleos y disfruta como nunca antes de apps y juegos con gráficos avanzados gracias al GPU de hasta 8 núcleos. Además, el Neural Engine de 16 núcleos se encarga de acelerar todos los procesos de aprendizaje automático. Todo en un diseño silencioso sin ventilador que te ofrece la mayor duración de batería en una MacBook Air: hasta 18 horas. (1) Portátil como siempre, más poderosa que nunca.",
    serie: "A2337",
    year: "2020",
    ram: "8 GB",
    resolution: "full HD",
    screen: "13.3",
    battery: "18 h",
    chip: "M1",
    ssd: "256 GB",
    color: "Negro",
  },
];

export { data };
